server:
  port: 5555

  #Setting logging levels
logging:
  level:
    com.netflix: INFO
    org.springframework.web: INFO
    com.ivan.spring: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  zipkin:
    base-url: http://localhost:9411
